# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='storage',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='资源'),
        ),
    ]
