# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-24 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('tech_stack', models.CharField(choices=[('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('PHP', 'PHP')], max_length=50, verbose_name='技术栈')),
                ('content', models.TextField(verbose_name='内容')),
                ('published', models.BooleanField(default=False, verbose_name='发布')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_authors', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
            },
        ),
    ]
