# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='tech_stack',
            field=models.CharField(choices=[('OTHER', '其它'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('PHP', 'PHP'), ('CACHE', '缓存'), ('BIGDATA', '大数据'), ('DATABASE', '数据库')], max_length=50, verbose_name='技术栈'),
        ),
    ]
