# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20180829_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='tech_stack',
            field=models.CharField(blank=True, choices=[('OTHER', '其它'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('PHP', 'PHP'), ('CACHE', '缓存'), ('BIGDATA', '大数据'), ('DATABASE', '数据库')], default='OTHER', max_length=50, null=True, verbose_name='技术栈'),
        ),
    ]
