# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_auto_20180829_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='关键则')),
                ('count', models.IntegerField(default=1, verbose_name='次数')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name_plural': '热门搜索',
                'verbose_name': '热门搜索',
            },
        ),
    ]
