# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_popularkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularkeyword',
            name='keyword',
            field=models.CharField(max_length=200, unique=True, verbose_name='关键则'),
        ),
    ]
