# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-04 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0010_auto_20180831_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏日期')),
            ],
            options={
                'verbose_name': '个人收藏',
                'verbose_name_plural': '个人收藏',
            },
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['-update_at'], 'verbose_name': '文档', 'verbose_name_plural': '文档'},
        ),
        migrations.AddField(
            model_name='favorite',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_docs', to='doc.Doc', verbose_name='文档'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to=settings.AUTH_USER_MODEL, verbose_name='收藏人'),
        ),
    ]
