# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-04 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_auto_20180904_0932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([]),
        ),
    ]
