# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-04 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0013_auto_20180904_0933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('doc', 'user')]),
        ),
    ]
