# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_auto_20180904_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-create_at'], 'verbose_name': '个人收藏', 'verbose_name_plural': '个人收藏'},
        ),
    ]
