# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-10 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0015_auto_20180904_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='归档名称')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建档日期')),
                ('docs', models.ManyToManyField(to='doc.Doc', verbose_name='文档')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_owners', to=settings.AUTH_USER_MODEL, verbose_name='所属人')),
            ],
            options={
                'verbose_name_plural': '归档整理',
                'verbose_name': '归档整理',
            },
        ),
        migrations.AlterUniqueTogether(
            name='archive',
            unique_together=set([('name', 'owner')]),
        ),
    ]
